version: "3.9"

services:
  zenndocc:
    container_name: zenndocc
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/workspace:delegated
      - node_modules:/workspace/node_modules
    ports:
      - 8008:8000
    restart: always

volumes:
  node_modules:
